version: '3.8'
services:
  db:
    image: postgres:13.5
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5533:5432'
volumes:
  postgres:
